version: '3.8'

services:
  next-app:
    image: ghcr.io/rbreham/next-cda241/next-app:latest
    container_name: next-app
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "80:3000"