version: '3.8'

services:
  next-app:
    build:
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - "80:3000"
    volumes:
      - .:/app
    command: ['npm', 'run', 'dev']