name: Docker Deployment pipeline main

on:
  push:
    branches: ['develop']

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image (linux/amd64)
        run: |
          docker build --platform linux/amd64 -t ghcr.io/rbreham/next-cda241/next-app:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/rbreham/next-cda241/next-app:latest

  build-deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Remote SSH deploy
        run: |
            ssh -i ~/.ssh/id_rsa.pem ubuntu@ec2-13-216-58-120.compute-1.amazonaws.com << EOF
                cd next-cda241
                sudo docker-compose pull
                sudo docker-compose -f docker-compose-produ-yml up -d
            EOF